import { mockup_users } from 'root/mockup/users';
import { IProject, ProjectVisibilty, TaskStatus } from 'utils/types/Project';

export const mockup_projects: IProject[] = [
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/moon.png',
        start_date: '2022-09-15',
        end_date: '2022-09-28',
        is_complete: false,
        visibility: ProjectVisibilty.PUBLIC,
        department: 'Sport',
        title: 'Fitness app project',
        manager: mockup_users[1],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                title: 'Home task',
                bounty: 3350,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(0, 3),
                deadline: '2022-09-24',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description:
                    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis assumenda porro cumque rerum quod illo cum ipsa numquam ipsam aliquam.',
                attachments: [
                    'Presentation.fig',
                    '/mockup/img/attachment-1.png',
                    'User Flow.fig',
                    'Logo.svg',
                    'Melody.mp3',
                ],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(2, 4),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.IN_WORK,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-2.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 131072,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed4',
                title: 'Mockups 3',
                bounty: 7000,
                pos: 65536,
                category: 'Design',
                comments: [''],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-27',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-25',
                created_at: '2022-09-22',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed5',
                title: 'Mockups',
                bounty: 10000,
                category: 'Design',
                comments: [],
                contributors: mockup_users.slice(3, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                pos: 65536,
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
                title: 'Mockups 2',
                bounty: 10000,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 4),
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                pos: 131072,
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-19',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 196608,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-15',
        created_at: '2022-09-15',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/heart.png',
        start_date: '2022-09-08',
        end_date: '2022-09-29',
        is_complete: false,
        visibility: ProjectVisibilty.PUBLIC,
        department: 'Design',
        title: 'Design project',
        manager: mockup_users[2],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                title: 'Home task',
                bounty: 3350,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 4),
                deadline: '2022-09-24',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description:
                    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis assumenda porro cumque rerum quod illo cum ipsa numquam ipsam aliquam.',
                attachments: [
                    'Presentation.fig',
                    '/mockup/img/attachment-3.png',
                    'User Flow.fig',
                    'Logo.svg',
                    'Melody.mp3',
                ],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 1),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.IN_WORK,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-1.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 131072,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed4',
                title: 'Mockups 3',
                bounty: 7000,
                pos: 65536,
                category: 'Design',
                comments: [''],
                contributors: mockup_users.slice(0, 3),
                deadline: '2022-09-27',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-25',
                created_at: '2022-09-22',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-04',
        created_at: '2022-09-04',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/runner.png',
        start_date: '2022-09-04',
        end_date: '2022-09-07',
        is_complete: false,
        visibility: ProjectVisibilty.MEMBER,
        department: 'sport',
        title: 'Sleep app project',
        manager: mockup_users[3],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                title: 'Home task',
                bounty: 3350,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-24',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description:
                    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis assumenda porro cumque rerum quod illo cum ipsa numquam ipsam aliquam.',
                attachments: [
                    'Presentation.fig',
                    '/mockup/img/attachment-2.png',
                    'User Flow.fig',
                    'Logo.svg',
                    'Melody.mp3',
                ],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.IN_WORK,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-3.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 131072,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed4',
                title: 'Mockups 3',
                bounty: 7000,
                pos: 65536,
                category: 'Design',
                comments: [''],
                contributors: mockup_users.slice(3, 7),
                deadline: '2022-09-27',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-25',
                created_at: '2022-09-22',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-04',
        created_at: '2022-09-04',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed4',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/hand-clock.png',
        start_date: '2022-09-04',
        end_date: '2022-09-08',
        is_complete: false,
        visibility: ProjectVisibilty.MEMBER,
        department: 'sport',
        title: 'Sleep app project',
        manager: mockup_users[4],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                title: 'Home task',
                bounty: 3350,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-24',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description:
                    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis assumenda porro cumque rerum quod illo cum ipsa numquam ipsam aliquam.',
                attachments: [
                    'Presentation.fig',
                    '/mockup/img/attachment-1.png',
                    'User Flow.fig',
                    'Logo.svg',
                    'Melody.mp3',
                ],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.IN_WORK,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-2.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 131072,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed4',
                title: 'Mockups 3',
                bounty: 7000,
                pos: 65536,
                category: 'Design',
                comments: [''],
                contributors: mockup_users.slice(3, 7),
                deadline: '2022-09-27',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-25',
                created_at: '2022-09-22',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-08',
        created_at: '2022-09-08',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed5',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/user-laptop.png',
        start_date: '2022-09-01',
        end_date: '2022-09-15',
        is_complete: false,
        visibility: ProjectVisibilty.PUBLIC,
        department: 'Development',
        title: 'Develop app project',
        manager: mockup_users[5],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                title: 'Home task',
                bounty: 3350,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-24',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description:
                    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis assumenda porro cumque rerum quod illo cum ipsa numquam ipsam aliquam.',
                attachments: [
                    'Presentation.fig',
                    '/mockup/img/attachment-2.png',
                    'User Flow.fig',
                    'Logo.svg',
                    'Melody.mp3',
                ],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.IN_WORK,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-3.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 131072,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed4',
                title: 'Mockups 3',
                bounty: 7000,
                pos: 65536,
                category: 'Design',
                comments: [''],
                contributors: mockup_users.slice(3, 7),
                deadline: '2022-09-27',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-25',
                created_at: '2022-09-22',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed5',
                title: 'Mockups',
                bounty: 10000,
                pos: 65536,
                category: 'Design',
                comments: [],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
                title: 'Mockups 2',
                bounty: 10000,
                pos: 131072,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-19',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 196608,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-12',
        created_at: '2022-09-12',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/iphone.png',
        start_date: '2022-09-11',
        end_date: '2022-09-22',
        is_complete: true,
        visibility: ProjectVisibilty.PUBLIC,
        department: 'Development',
        title: 'Develop app project',
        manager: mockup_users[6],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                title: 'Home task',
                bounty: 3350,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-24',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description:
                    'Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis assumenda porro cumque rerum quod illo cum ipsa numquam ipsam aliquam.',
                attachments: [
                    'Presentation.fig',
                    '/mockup/img/attachment-1.png',
                    'User Flow.fig',
                    'Logo.svg',
                    'Melody.mp3',
                ],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-16',
                created_at: '2022-09-16',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 131072,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-2.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 196608,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
                title: 'Mockups 2',
                bounty: 10000,
                pos: 262144,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-19',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 327680,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-01',
        created_at: '2022-09-01',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/books.png',
        start_date: '2022-09-02',
        end_date: '2022-09-15',
        is_complete: true,
        visibility: ProjectVisibilty.MEMBER,
        department: 'Design',
        title: 'Design app project',
        manager: mockup_users[7],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-3.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 131072,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
                title: 'Mockups 2',
                bounty: 10000,
                pos: 196608,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-19',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 262144,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-04',
        created_at: '2022-09-04',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed8',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/heart.png',
        start_date: '2022-08-27',
        end_date: '2022-09-02',
        is_complete: false,
        visibility: ProjectVisibilty.PUBLIC,
        department: 'Design',
        title: 'Design app project',
        manager: mockup_users[1],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-3.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 65536,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
                title: 'Mockups 2',
                bounty: 10000,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(2, 6),
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-19',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 131072,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(0, 7),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-08-25',
        created_at: '2022-08-25',
    },
    {
        id: '6b40768b-2919-4c4c-a0c3-182dca528ed9',
        dao_id: '237fh588b-24-4c4c-a0c3-jj37r791e',
        icon: '/img/icons/heart.png',
        start_date: '2022-08-27',
        end_date: '2022-10-11',
        is_complete: false,
        visibility: ProjectVisibilty.MEMBER,
        department: 'Sport',
        title: 'Run app project',
        manager: mockup_users[3],
        tasks: [
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed2',
                title: 'Develop calculator',
                bounty: 10000,
                pos: 65536,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(2, 4),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', '/mockup/img/attachment-3.png', 'User Flow.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-18',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed3',
                title: 'Find candidats',
                bounty: 12000,
                pos: 65536,
                category: 'Managment',
                comments: ['', '', '', '', ''],
                contributors: [],
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.REVIEW,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-18',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed6',
                title: 'Mockups 2',
                bounty: 10000,
                pos: 65536,
                category: 'Design',
                comments: ['', ''],
                contributors: mockup_users.slice(1, 5),
                deadline: '2022-09-25',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.NOT_STARTED,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Presentation.fig', 'Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-19',
                created_at: '2022-09-19',
            },
            {
                id: '6b40768b-2919-4c4c-a0c3-182dca528ed7',
                title: 'Fix design',
                bounty: 10000,
                pos: 131072,
                category: 'Developing',
                comments: [],
                contributors: mockup_users.slice(),
                deadline: '2022-09-28',
                github: null,
                labels: [
                    { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
                    { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
                    { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
                    { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
                    { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
                ],
                status: TaskStatus.DONE,
                description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
                attachments: ['Reference.mp4'],
                project_id: '6b40768b-2919-4c4c-a0c3-182dca528ed1',
                updated_at: '2022-09-24',
                created_at: '2022-09-24',
            },
        ],
        updated_at: '2022-09-20',
        created_at: '2022-09-20',
    },
];
