import { IUser, Roles, UserRating } from 'utils/types/User';

export const mockup_users: (IUser & {
    member: { username: string; name: string; profile_picture: string };
})[] = [
    {
        id: '1',
        link: 'alexalorem',
        fullname: 'Alex Alorem',
        location: 'San Francisco, California',
        avatar: '/mockup/img/header-avatar.png',
        rating: UserRating.A,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        profession: 'Senior UI Designer',
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.ADMIN,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
    {
        id: '2',
        link: 'alenawilliams',
        fullname: 'Alena Williams',
        location: 'San Francisco, California',
        avatar: '/mockup/img/user-1.png',
        rating: UserRating.C,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        profession: 'Senior UI Designer',
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.CAPTAIN,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
    {
        id: '3',
        link: 'marvin',
        fullname: 'Phylp Marvin',
        location: 'San Francisco, California',
        avatar: '/mockup/img/user-2.png',
        rating: UserRating.C,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        profession: 'Senior UI Designer',
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.CONTRIBUTOR,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
    {
        id: '4',
        link: 'phyllishall',
        fullname: 'Phyllis Hall',
        location: 'San Francisco, California',
        avatar: '/mockup/img/user-3.png',
        rating: UserRating.C,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        profession: 'Senior Software Developer',
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.ADMIN,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
    {
        id: '5',
        link: 'dianaaa',
        fullname: 'Diana Adams',
        location: 'San Francisco, California',
        avatar: '/mockup/img/user-5.png',
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        rating: UserRating.A,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        profession: 'Senior Software Developer',
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.CAPTAIN,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
    {
        id: '6',
        link: 'doe_john',
        fullname: 'John Doe',
        location: 'San Francisco, California',
        avatar: '/mockup/img/user-2.png',
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        rating: UserRating.B,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        profession: 'Senior Software Developer',
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.CONTRIBUTOR,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
    {
        id: '7',
        link: 'l3stlee',
        fullname: 'Rebecca Lestlee',
        location: 'San Francisco, California',
        avatar: '/mockup/img/user-2.png',
        rating: UserRating.B,
        education: 'Stanford University',
        languages: ['English', 'Spanish'],
        member: {
            name: 'sdsd',
            username: 'sdssd',
            profile_picture: '/img/user-4.png',
        },
        profession: 'Senior Software Developer',
        about: 'I live in any area that drives experience — whether it’s initial exploration, critically refining user flows and functionality, or polishing the visuals. I help businesses develop their product and iterate quickly to deliver meaningful, successful results.',
        private: false,
        open_for_jobs: true,
        balance: {
            btc: 0.58966452,
        },
        socials: {
            discord: null,
            linkedIn: null,
            github: null,
            behance: '/#behance',
            dribbble: '/#dribbble',
        },
        skills: [
            { id: 1, name: 'Product Design', icon: '/img/skills/product.svg' },
            { id: 2, name: 'Design systems', icon: '/img/skills/systems.svg' },
            { id: 3, name: 'UI Design', icon: '/img/skills/ui.svg' },
            { id: 4, name: 'User Flow', icon: '/img/skills/user_flow.svg' },
            { id: 5, name: 'User Research', icon: '/img/skills/user_research.svg' },
        ],
        role: Roles.CAPTAIN,
        updated_at: '2022-05-12',
        created_at: '2022-05-12',
    },
];
