#!/bin/bash

set -e

export SERVICE_NAME=service-analytics
export PORT=4009
export MONGO_URL=$MONGO_URL_LOCAL_PLUGIN

go test ./...
go build -tags=jsoniter -o build/service-analytics
./build/service-analytics
