kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway-consumer
  labels:
    app: gateway-consumer
data:
  jwt-key: <jwt-key>
  aws-access-key-id: <aws-access-key-id>
  aws-secret-access-key: <aws-secret-access-key>
  spaces-endpoint: <spaces-endpoint> # we were using digitalocean spaces
  spaces-cdn: <spaces-cdn>
  spaces-region: <spaces-region>
  parcel-app-token: <parcel-app-token>
  redis-database-url: redis://:$(REDIS_PASSWORD)@redis-service.default.svc.cluster.local:6379
  lighthouse-token: <lighthouse-token>
  neynar-api-key: <neynar-api-key>
  twitter-client-id: <twitter-client-id>
  stripe-secret-key: <stripe-secret-key>
  stripe-webhook-signing-secret: <stripe-webhook-signing-secret>
  stripe-monthly-price-id: <stripe-monthly-price-id>
  stripe-yearly-price-id: <stripe-yearly-price-id>
  stripe-product-id: <stripe-product-id>
  samudai-mail: <samudai-mail>
  samudai-mail-password: <samudai-mail-password>
  default-connection-members: <default-connection-members>
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-consumer-node
  labels:
    app: gateway-consumer-node
  annotations:
    externalTrafficPolicy: Local
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: gateway-consumer-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-consumer-node
spec:
  selector:
    matchLabels:
      app: gateway-consumer-node
  revisionHistoryLimit: 2
  replicas: 7
  strategy:
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gateway-consumer-node
    spec:
      containers:
        - name: gateway-consumer-node
          image: ghcr.io/samudai/gateway-consumer-node:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: jwt-key
            - name: ENVIRONMENT
              value: prod
            - name: SERVICE_MEMBER
              value: http://service-member
            - name: SERVICE_DISCORD
              value: http://service-discord
            - name: SERVICE_PROJECT
              value: http://service-project
            - name: SERVICE_PLUGIN
              value: http://service-plugin
            - name: SERVICE_JOB
              value: http://service-job
            - name: SERVICE_DAO
              value: http://service-dao
            - name: SERVICE_DASHBOARD
              value: http://service-dashboard
            - name: SERVICE_DISCUSSION
              value: http://service-discussion
            - name: SERVICE_FORMS
              value: http://service-forms
            - name: SERVICE_PAYMENT
              value: http://service-payment
            - name: SERVICE_TWITTER
              value: http://service-twitter
            - name: SERVICE_ACTIVITY
              value: http://service-activity
            - name: SERVICE_WEB3
              value: http://service-web3
            - name: SERVICE_DISCOVERY
              value: http://service-discovery
            - name: SERVICE_POINT
              value: http://service-point
            - name: GATEWAY_EXTERNAL
              value: http://gateway-external
            - name: SAMUDAI_BOT
              value: http://samudai-bot
            - name: TRIAL_DASHBOARD
              value: 605a8aa8-fa7c-4a9c-8723-8078c3a0e014
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: redis-database-url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: aws-access-key-id
            - name: AWS_SCERET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: aws-secret-access-key
            - name: SPACES_BUCKET
              value: samudai
            - name: SPACES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: spaces-endpoint
            - name: SPACES_CDN
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: spaces-cdn
            - name: SPACES_REGION
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: spaces-region
            - name: PARCEL_APP_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: parcel-app-token
            - name: ELASTIC_APM_SERVICE_NAME
              value: gateway-consumer
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-sercret-token
            - name: ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-env
            - name: DEFAULT_CONNECTION_MEMBERS
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: default-connection-members
            - name: SAMUDAI_URL
              value: https://app.samudai.xyz
            - name: GCN_URL
              value: https://gcn.samudai.xyz
            - name: LIGHTHOUSE_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: lighthouse-token
            - name: NEYNAR_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: neynar-api-key
            - name: TWITTER_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: twitter-client-id
            - name: STRIPE_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: stripe-secret-key
            - name: STRIPE_WEBHOOK_SIGNING_SECRET
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: stripe-webhook-signing-secret
            - name: STRIPE_MONTHLY_PRICE_ID
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: stripe-monthly-price-id
            - name: STRIPE_YEARLY_PRICE_ID
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: stripe-yearly-price-id
            - name: STRIPE_PRODUCT_ID
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: stripe-product-id
            - name: SAMUDAI_MAIL
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: samudai-mail
            - name: SAMUDAI_MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: gateway-consumer
                  key: samudai-mail-password
