apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # These are base64 encoded values. In production, use more secure passwords
  POSTGRES_USER: cG9zdGdyZXM= # 'postgres' in base64
  POSTGRES_PASSWORD: cG9zdGdyZXM= # 'postgres' in base64
