apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  # Base64 encoded values
  RABBITMQ_DEFAULT_USER: YWRtaW4= # admin
  RABBITMQ_DEFAULT_PASS: cmFiYml0bXFwYXNz # rabbitmqpass
