kind: ConfigMap
apiVersion: v1
metadata:
  name: service-discord
  labels:
    app: service-discord
data:
  # Configuration values can be set as key-value properties
  discord-client-id: <discord-client-id>
  discord-client-secret: <discord-client-secret>
  mongo-database-url: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service.default.svc.cluster.local:27017/default?authSource=admin
  mq-ip: rabbitmq-service.default.svc.cluster.local
  mq-username: $(RABBITMQ_DEFAULT_USER)
  mq-password: $(RABBITMQ_DEFAULT_PASS)
---
apiVersion: v1
kind: Service
metadata:
  name: service-discord
  labels:
    app: service-discord
  annotations:
    prometheus.io/probe: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: service-discord
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discord
spec:
  selector:
    matchLabels:
      app: service-discord
  revisionHistoryLimit: 2
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: service-discord
    spec:
      containers:
        - name: service-discord
          image: ghcr.io/samudai/service-discord:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: service-discord
          resources:
            limits:
              cpu: 100m
          env:
            - name: GIN_MODE
              value: release
            - name: SERVICE_NAME
              value: service-discord
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_POINT
              value: http://service-point
            - name: MORALIS_API_KEY
              value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6IjAzODA1OGIzLTNmMDItNGRiOS05ODZlLTA4MmNmMDk0MTdlOSIsIm9yZ0lkIjoiMzg5NzU4IiwidXNlcklkIjoiNDAwNTAyIiwidHlwZUlkIjoiZGNlZWZjYTAtOTc2ZS00Y2JhLTk0YTItNDg3OTI0MTM2YTBkIiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3MTQxNTg5NTQsImV4cCI6NDg2OTkxODk1NH0.7cbiet5xi982yvzIIwhxnRBuo6zzCRDFMx5ETjtpo5I"
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: mongo-database-url
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: redis-database-url
            - name: DISCORD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: discord-client-id
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: discord-client-secret
            - name: MQ_IP
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: mq-ip
            - name: MQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: mq-username
            - name: MQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: service-discord
                  key: mq-password
            - name: ELASTIC_APM_SERVICE_NAME
              value: service-discord
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-sercret-token
            - name: ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-env
