kind: ConfigMap
apiVersion: v1
metadata:
  name: service-member
  labels:
    app: service-member
data:
  # Configuration values can be set as key-value properties
  pg-database-url: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/member?sslmode=disable
---
apiVersion: v1
kind: Service
metadata:
  name: service-member
  labels:
    app: service-member
  annotations:
    prometheus.io/probe: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: service-member
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-member
spec:
  selector:
    matchLabels:
      app: service-member
  revisionHistoryLimit: 2
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: service-member
    spec:
      containers:
        - name: service-member
          image: ghcr.io/samudai/service-member:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: service-member
          resources:
            limits:
              cpu: 50m
          env:
            - name: SERVICE_NAME
              value: service-member
            - name: GIN_MODE
              value: release
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: service-member
                  key: pg-database-url
            - name: ELASTIC_APM_SERVICE_NAME
              value: service-member
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-sercret-token
            - name: ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-env
