kind: ConfigMap
apiVersion: v1
metadata:
  name: service-member
  labels:
    app: service-member
data:
  # Configuration values can be set as key-value properties
  pg-database-url: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/member?sslmode=disable
