kind: ConfigMap
apiVersion: v1
metadata:
  name: service-plugin
  labels:
    app: service-plugin
data:
  # Configuration values can be set as key-value properties
  notion-client-id: <notion-client-id>
  notion-client-secret: <notion-client-secret>
  mongo-database-url: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service.default.svc.cluster.local:27017/?authSource=admin
  github-app-id: <github-app-id>
  github-app-webhook-secret: <github-app-webhook-secret>
  github-app-client-id: <github-app-client-id>
  github-app-client-secret: <github-app-client-secret>
  github-oauth-app-client-id: <github-oauth-app-client-id>
  github-oauth-app-client-secret: <github-oauth-app-client-secret>
  gcal-client-id: <gcal-client-id>
  gcal-client-secret: <gcal-client-secret>
  gcal-project-id: <gcal-project-id>
