kind: ConfigMap
apiVersion: v1
metadata:
  name: service-discord
  labels:
    app: service-discord
data:
  # Configuration values can be set as key-value properties
  discord-client-id: <discord-client-id>
  discord-client-secret: <discord-client-secret>
  mongo-database-url: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service.default.svc.cluster.local:27017/default?authSource=admin
  mq-ip: rabbitmq-service.default.svc.cluster.local
  mq-username: $(RABBITMQ_DEFAULT_USER)
  mq-password: $(RABBITMQ_DEFAULT_PASS)
