kind: ConfigMap
apiVersion: v1
metadata:
  name: service-web3
  labels:
    app: service-web3
data:
  # Configuration values can be set as key-value properties
  mongo-database-url: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service.default.svc.cluster.local:27017/web3?authSource=admin
