kind: ConfigMap
apiVersion: v1
metadata:
  name: service-web3
  labels:
    app: service-web3
data:
  # Configuration values can be set as key-value properties
  mongo-database-url: mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongodb-service.default.svc.cluster.local:27017/web3?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: service-web3
  labels:
    app: service-web3
  annotations:
    prometheus.io/probe: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: service-web3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-web3
spec:
  selector:
    matchLabels:
      app: service-web3
  revisionHistoryLimit: 2
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: service-web3
    spec:
      containers:
        - name: service-web3
          image: ghcr.io/samudai/service-web3:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
          env:
            - name: SERVICE_DISCOVERY
              value: http://service-discovery
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: service-web3
                  key: mongo-database-url
            - name: ELASTIC_APM_SERVICE_NAME
              value: service-web3
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-sercret-token
            - name: ELASTIC_APM_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: elastic
                  key: elastic-apm-env
