kind: ConfigMap
apiVersion: v1
metadata:
  name: service-discussion
  labels:
    app: service-discussion
data:
  # Configuration values can be set as key-value properties
  pg-database-url: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/discussion?sslmode=disable
