kind: ConfigMap
apiVersion: v1
metadata:
  name: telegram-bot
  labels:
    app: telegram-bot
data:
  bot-id: <bot-id>
  mq-ip: rabbitmq-service.default.svc.cluster.local
  mq-username: $(RABBITMQ_DEFAULT_USER)
  mq-password: $(RABBITMQ_DEFAULT_PASS)
