on:
  push:
    branches:
      - master
    paths:
      - services/service-discord/**

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/samudai/service-discord
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: services/service-discord
          file: services/service-discord/Dockerfile
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/samudai/service-discord:${{ github.sha }}
            ghcr.io/samudai/service-discord:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
