--
-- PostgreSQL database dump
--


-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.access (
    id bigint NOT NULL,
    point_id uuid,
    access text,
    members uuid[] DEFAULT '{}'::uuid[],
    roles uuid[] DEFAULT '{}'::uuid[],
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: access_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.access ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.access_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contract (
    id bigint NOT NULL,
    point_id uuid,
    contract_address text,
    topic text,
    points_num integer,
    event text,
    name text,
    chain_id text,
    pertoken_points_num integer,
    all_events text,
    event_nft_address text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: contract_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_product_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_product_events (
    id bigint NOT NULL,
    product_id uuid,
    point_id uuid,
    event_name text,
    points_num double precision,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: custom_product_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_product_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_product_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_product_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_product_members (
    id bigint NOT NULL,
    point_id uuid,
    member_id uuid,
    product_id uuid,
    unique_user_id text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: custom_product_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_product_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_product_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_products (
    product_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    point_id uuid,
    name text,
    logo text,
    description text,
    whitelisted_origins text[] DEFAULT '{}'::text[],
    is_active boolean DEFAULT true,
    referral_points_num double precision DEFAULT 0,
    same_referral_points_user_joining boolean DEFAULT false,
    referral_is_active boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: discord; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord (
    discord_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    member_id uuid NOT NULL,
    discord_user_id character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    username text,
    avatar text,
    discriminator text,
    public_flags integer,
    flags integer,
    banner text,
    banner_color text,
    accent_color integer,
    locale text,
    mfa_enabled boolean DEFAULT false,
    verified boolean DEFAULT false,
    email text
);


--
-- Name: member_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_points (
    member_point_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    member_id uuid NOT NULL,
    point_id uuid NOT NULL,
    access text[] DEFAULT '{}'::text[],
    roles jsonb DEFAULT '[]'::jsonb,
    member_joined_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    points double precision DEFAULT 0
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    member_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255),
    email character varying(255),
    wallet_address character varying(255),
    chain_id character varying(50),
    email_verified boolean DEFAULT false,
    email_verification_code character varying(255),
    is_onboarded boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: point; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.point (
    point_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    id bigint NOT NULL,
    guild_id text,
    email text,
    server_name text
);


--
-- Name: member_points_view; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.member_points_view AS
 SELECT p.id,
    mp.member_id,
    mp.point_id,
    p.name,
    p.guild_id,
    mp.roles,
    mp.access,
    p.created_at AS point_created,
    p.updated_at AS point_updated,
    mp.member_joined_at AS member_joined,
    mp.points,
    p.server_name,
    jsonb_build_object('member_id', m.member_id, 'name', m.name, 'email', m.email, 'wallet_address', m.wallet_address, 'chain_id', m.chain_id, 'email_verified', m.email_verified, 'is_onboarded', m.is_onboarded, 'created_at', m.created_at) AS member
   FROM ((public.member_points mp
     JOIN public.members m ON ((m.member_id = mp.member_id)))
     JOIN public.point p ON ((p.point_id = mp.point_id)));


--
-- Name: member_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_roles (
    id bigint NOT NULL,
    point_id uuid,
    member_id uuid,
    role_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: member_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: point_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.point ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referral_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referral_members (
    id bigint NOT NULL,
    point_id uuid,
    product_id uuid,
    unique_user_id text,
    referral_code text DEFAULT substr(md5((random())::text), 1, 8),
    users_invited integer DEFAULT 0,
    invited_user_ids text[] DEFAULT '{}'::text[],
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: referral_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referral_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referral_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    point_id uuid,
    name text,
    discord_role_id text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: telegram; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telegram (
    telegram_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    member_id uuid,
    point_id uuid,
    chat_id text,
    chat_type text,
    username text,
    first_name text,
    last_name text,
    otp text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: telegram_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telegram_points (
    id bigint NOT NULL,
    point_id uuid,
    event_name text,
    points_num double precision,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: telegram_points_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.telegram_points ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telegram_points_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: twitter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twitter (
    twitter_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    point_id uuid,
    twitter_username text,
    twitter_user_id text,
    access_token text,
    refresh_token text,
    client_type text,
    is_active boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: twitter_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twitter_members (
    member_id uuid,
    twitter_username text,
    twitter_user_id text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: twitter_points; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twitter_points (
    point_id uuid,
    tweet_id text[] DEFAULT '{}'::text[],
    follow integer DEFAULT 0,
    mention integer DEFAULT 0,
    likes integer DEFAULT 0,
    retweet integer DEFAULT 0,
    quote integer DEFAULT 0,
    hashtag text,
    hashtag_pts integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: webhooks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhooks (
    id bigint NOT NULL,
    point_id uuid,
    contract_address text,
    webhook_id text,
    is_active boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: webhooks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.webhooks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.webhooks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: access access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.access
    ADD CONSTRAINT access_pkey PRIMARY KEY (id);


--
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- Name: custom_product_events custom_product_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_product_events
    ADD CONSTRAINT custom_product_events_pkey PRIMARY KEY (id);


--
-- Name: custom_product_members custom_product_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_product_members
    ADD CONSTRAINT custom_product_members_pkey PRIMARY KEY (id);


--
-- Name: custom_product_members custom_product_members_product_id_member_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_product_members
    ADD CONSTRAINT custom_product_members_product_id_member_id_key UNIQUE (product_id, member_id);


--
-- Name: custom_products custom_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_products
    ADD CONSTRAINT custom_products_pkey PRIMARY KEY (product_id);


--
-- Name: discord discord_discord_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord
    ADD CONSTRAINT discord_discord_user_id_key UNIQUE (discord_user_id);


--
-- Name: discord discord_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord
    ADD CONSTRAINT discord_pkey PRIMARY KEY (discord_id);


--
-- Name: member_points member_points_member_id_point_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points
    ADD CONSTRAINT member_points_member_id_point_id_key UNIQUE (member_id, point_id);


--
-- Name: member_points member_points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points
    ADD CONSTRAINT member_points_pkey PRIMARY KEY (member_point_id);


--
-- Name: member_roles member_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_roles
    ADD CONSTRAINT member_roles_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (member_id);


--
-- Name: point points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.point
    ADD CONSTRAINT points_pkey PRIMARY KEY (point_id);


--
-- Name: referral_members referral_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referral_members
    ADD CONSTRAINT referral_members_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: telegram telegram_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telegram
    ADD CONSTRAINT telegram_pkey PRIMARY KEY (telegram_id);


--
-- Name: telegram_points telegram_points_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telegram_points
    ADD CONSTRAINT telegram_points_pkey PRIMARY KEY (id);


--
-- Name: twitter twitter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twitter
    ADD CONSTRAINT twitter_pkey PRIMARY KEY (twitter_id);


--
-- Name: webhooks webhooks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhooks
    ADD CONSTRAINT webhooks_pkey PRIMARY KEY (id);


--
-- Name: idx_discord_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_discord_member ON public.discord USING btree (member_id);


--
-- Name: idx_member_points_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_member_points_member ON public.member_points USING btree (member_id);


--
-- Name: idx_member_points_point; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_member_points_point ON public.member_points USING btree (point_id);


--
-- Name: idx_members_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_members_email ON public.members USING btree (email);


--
-- Name: idx_members_wallet; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_members_wallet ON public.members USING btree (wallet_address);


--
-- Name: idx_point_guild; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_point_guild ON public.point USING btree (guild_id);


--
-- Name: idx_telegram_chat_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_telegram_chat_id ON public.telegram USING btree (chat_id);


--
-- Name: idx_telegram_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_telegram_username ON public.telegram USING btree (username);


--
-- Name: idx_twitter_members_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_twitter_members_member ON public.twitter_members USING btree (member_id);


--
-- Name: discord discord_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord
    ADD CONSTRAINT discord_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id);


--
-- Name: member_points member_points_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points
    ADD CONSTRAINT member_points_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.members(member_id);


--
-- Name: member_points member_points_point_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_points
    ADD CONSTRAINT member_points_point_id_fkey FOREIGN KEY (point_id) REFERENCES public.point(point_id);


--
-- PostgreSQL database dump complete
--


