-- 000002_point_service_fixes.up.sql
-- Reconcile committed schema with the SQL the point service actually executes.
-- Idempotent: safe on both fresh and already-applied databases.

-- ---------------------------------------------------------------------------
-- 1. Rename table points -> point (guarded; preserves member_points FK).
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'points')
       AND NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'point') THEN
        ALTER TABLE points RENAME TO point;
    END IF;
END $$;

-- Fresh-DB path: 000001 created "points"; on a brand-new DB the rename above
-- handles it. This guarantees "point" exists either way.
CREATE TABLE IF NOT EXISTS point (
    point_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 2. Add columns to point.
--    point.go:122 selects id (scanned into PointView.ID int) -> bigint identity.
--    guild_id/email/server_name selected & written in point.go.
-- ---------------------------------------------------------------------------
ALTER TABLE point ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE point ADD COLUMN IF NOT EXISTS guild_id TEXT;
ALTER TABLE point ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE point ADD COLUMN IF NOT EXISTS server_name TEXT;

-- ---------------------------------------------------------------------------
-- 3. member_points.points (mv.points; PointMember.Points float64 -> double precision).
-- ---------------------------------------------------------------------------
ALTER TABLE member_points ADD COLUMN IF NOT EXISTS points DOUBLE PRECISION DEFAULT 0;

-- ---------------------------------------------------------------------------
-- 4. Add columns to discord (discord.go INSERT/Scan list).
--    public_flags/flags int, accent_color *int, mfa_enabled/verified bool.
-- ---------------------------------------------------------------------------
ALTER TABLE discord ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS discriminator TEXT;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS public_flags INTEGER;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS flags INTEGER;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS banner TEXT;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS banner_color TEXT;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS accent_color INTEGER;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS locale TEXT;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT FALSE;
ALTER TABLE discord ADD COLUMN IF NOT EXISTS email TEXT;

-- ---------------------------------------------------------------------------
-- 5. roles table (role.go).
--    role_id RETURNED uuid; point_id ::uuid; name/discord_role_id text.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
    role_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    point_id UUID,
    name TEXT,
    discord_role_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 6. member_roles table (memberrole.go).
--    id RETURNED (scanned to string, deleted by int) -> bigint identity;
--    point_id/member_id/role_id ::uuid.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS member_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    member_id UUID,
    role_id UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 7. access table (access.go).
--    id (AccessView.AccessID string, scanned) -> bigint identity;
--    point_id ::uuid; access text; members/roles ::uuid[]; timestamps.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    access TEXT,
    members UUID[] DEFAULT '{}',
    roles UUID[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 8. telegram table (telegram.go, access.go).
--    telegram_id RETURNED uuid; member_id/point_id ::uuid; rest text.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telegram (
    telegram_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    member_id UUID,
    point_id UUID,
    chat_id TEXT,
    chat_type TEXT,
    username TEXT,
    first_name TEXT,
    last_name TEXT,
    otp TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 9. telegram_points table (telegram.go AddTelegramEventsPoint).
--    point_id ::uuid; event_name text; points_num float64 -> double precision.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telegram_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    event_name TEXT,
    points_num DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 10. twitter table (twitter.go).
--     twitter_id RETURNED uuid; point_id ::uuid; is_active bool; rest text.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS twitter (
    twitter_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    point_id UUID,
    twitter_username TEXT,
    twitter_user_id TEXT,
    access_token TEXT,
    refresh_token TEXT,
    client_type TEXT,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 11. twitter_members table (twittermember.go).
--     member_id ::uuid; twitter_username/twitter_user_id text.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS twitter_members (
    member_id UUID,
    twitter_username TEXT,
    twitter_user_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 12. twitter_points table (twitterevents.go).
--     point_id ::uuid; tweet_id pq.Array -> text[]; counts int; hashtag *string.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS twitter_points (
    point_id UUID,
    tweet_id TEXT[] DEFAULT '{}',
    follow INTEGER DEFAULT 0,
    mention INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    retweet INTEGER DEFAULT 0,
    quote INTEGER DEFAULT 0,
    hashtag TEXT,
    hashtag_pts INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 13. contract table (contract.go).
--     point_id ::uuid; points_num/pertoken_points_num []int -> integer;
--     all_events text; topic/event/name/chain_id/contract_address/
--     event_nft_address text.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    contract_address TEXT,
    topic TEXT,
    points_num INTEGER,
    event TEXT,
    name TEXT,
    chain_id TEXT,
    pertoken_points_num INTEGER,
    all_events TEXT,
    event_nft_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 14. webhooks table (contract.go).
--     point_id ::uuid; contract_address/webhook_id text; is_active bool.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS webhooks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    contract_address TEXT,
    webhook_id TEXT,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 15. custom_products table (customproduct.go).
--     product_id RETURNED on insert -> uuid; point_id ::? (no cast in code,
--     stored/compared as text-or-uuid; insert passes raw string) -> uuid;
--     whitelisted_origins pq.Array -> text[]; referral_points_num float64;
--     same_referral_points_user_joining / is_active / referral_is_active bool.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_products (
    product_id UUID DEFAULT uuid_generate_v4(),
    point_id UUID,
    name TEXT,
    logo TEXT,
    description TEXT,
    whitelisted_origins TEXT[] DEFAULT '{}',
    is_active BOOLEAN DEFAULT TRUE,
    referral_points_num DOUBLE PRECISION DEFAULT 0,
    same_referral_points_user_joining BOOLEAN DEFAULT FALSE,
    referral_is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id)
);

-- ---------------------------------------------------------------------------
-- 16. custom_product_events table (productevents.go).
--     product_id text; point_id ::uuid; event_name text;
--     points_num float64 -> double precision.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_product_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id UUID,
    point_id UUID,
    event_name TEXT,
    points_num DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 17. custom_product_members table (memberproduct.go).
--     ON CONFLICT (product_id, member_id) -> needs unique constraint.
--     point_id text; member_id/product_id ::uuid; unique_user_id text.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_product_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    member_id UUID,
    product_id UUID,
    unique_user_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, member_id)
);

-- ---------------------------------------------------------------------------
-- 18. referral_members table (customproduct.go).
--     referral_code RETURNED on insert with no value supplied -> needs DEFAULT
--     generator (format not specified anywhere in code; see report).
--     point_id/product_id text; unique_user_id text; users_invited int;
--     invited_user_ids array_append text -> text[].
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS referral_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_id UUID,
    product_id UUID,
    unique_user_id TEXT,
    referral_code TEXT DEFAULT substr(md5(random()::text), 1, 8),
    users_invited INTEGER DEFAULT 0,
    invited_user_ids TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- 19. Rebuild member_points_view (DROP+CREATE: leading column set/order/names
--     change vs 000001, so CREATE OR REPLACE is impossible).
--     Columns line up with point.go:55-56 Scan (12) PLUS member jsonb required
--     by member.go:43 ListPointMembers.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS member_points_view;
CREATE VIEW member_points_view AS
SELECT
    p.id                AS id,            -- &Point.ID (int)        <- point.id
    mp.member_id        AS member_id,     -- &Point.MemberID
    mp.point_id         AS point_id,      -- &Point.PointID
    p.name              AS name,          -- &Point.Name
    p.guild_id          AS guild_id,      -- &Point.GuildID
    mp.roles            AS roles,         -- *json.RawMessage (jsonb)
    mp.access           AS access,        -- pq.Array (text[])
    p.created_at        AS point_created, -- &Point.PointCreatedAt
    p.updated_at        AS point_updated, -- &Point.PointUpdatedAt
    mp.member_joined_at AS member_joined, -- &Point.MemberJoinedAt
    mp.points           AS points,        -- &Point.Points (double precision)
    p.server_name       AS server_name,   -- &Point.ServerName
    jsonb_build_object(                   -- member (member.go:43 ListPointMembers)
        'member_id', m.member_id,
        'name', m.name,
        'email', m.email,
        'wallet_address', m.wallet_address,
        'chain_id', m.chain_id,
        'email_verified', m.email_verified,
        'is_onboarded', m.is_onboarded,
        'created_at', m.created_at
    ) AS member
FROM member_points mp
JOIN members m ON m.member_id = mp.member_id
JOIN point p ON p.point_id = mp.point_id;

-- ---------------------------------------------------------------------------
-- 20. Indexes (no duplicates of 000001's idx_* set).
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_point_guild ON point(guild_id);
CREATE INDEX IF NOT EXISTS idx_telegram_username ON telegram(username);
CREATE INDEX IF NOT EXISTS idx_telegram_chat_id ON telegram(chat_id);
CREATE INDEX IF NOT EXISTS idx_twitter_members_member ON twitter_members(member_id);
